SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_BACKGROUND_COLOR = (255, 255, 255)

FIELD_WIDTH = 500
FIELD_HEIGHT = 500

CHARACTER_STARTING_SIZE = 10
CHARACTER_STARTING_SPEED = 1.5
CHARACTER_EAT_SIZE_GAIN_MULTIPLIER = 0.07
CHARACTER_EAT_CHARACTER_ADDITIONAL_GAIN = 2

BLOB_SIZE = 3

BLOB_SPAWNER_COOLDOWN = 500
BLOB_SPAWNER_RADIUS_VARIANCE = 50
BLOB_SPAWNER_RADIUS_MIN_ZONE = 50
BLOB_SPAWNER_MAX_PER_TICK = 50

# No more blobs than this should be on the field at the same time
BLOB_SPAWNER_UPPER_LIMIT = 200

CAMERA_CHARACTER_ZOOM_MULTIPLIER = 5

CHARACTER_SPAWNER_COOLDOWN = 1000
CHARACTER_SPAWNER_MAX_CHARACTERS = 10

BACKGROUND_SPEED_MULTIPLIER = 1

APP_SECONDS_BEFORE_END = 20
